### ISSUE TITLE
Rewrite for 0.4.0rc7

### ISSUE THREAD

**Issue by phated** [phated/grunt-jade#13]
Need to rewrite plugin using the new init template and make code more testable + add more tests.

**Comment by paulkarabilo** [comment]
Hi. Any progress with this issue? I've managed to make it work with grunt@0.4.0rc7, maybe this could help you: https://github.com/benizebe/grunt-jade/commit/5a1f39367e44002fa7824fe91075d43fc3a5f353

**Comment by phated** [comment]
This plugin now works with Grunt `~0.4.0`
