### ISSUE TITLE
Catch compile errors a little more gracefully....

### ISSUE THREAD

**Issue by jonsharratt** [phated/grunt-jade#14]
Heya,

Just a small change I feel we could do with looking into... in the helpers we could do with catching jade compile errors a little more gracefully so that when we use growl-notify it doesn't stop grunt continuing the watch tasks.

Will submit a pull request, just that we have a grunt task for development that will allow front-end devs to keep saving the jade file and recompile with growl notifying when a success or failure has happened with jade they have edited.

**Comment by phated** [comment]
Merged in to master - please upgrade to Grunt `~0.4.0`
