### ISSUE TITLE
How do I compile mutliple HTML Jade templates that use the same mixin

### ISSUE THREAD

**Issue by AJeezy9** [phated/grunt-jade#26]
```
mixin hero(title)
    .hero
        .hero__inner
            h1.hero__title #{title}
```

So, my project uses a Jade mixin like the above on multiple pages and, when I compile the Jade to HTML pages, I have to copy that mixin on each page that it is used.

Can this module be used to globally pass that mixin to all pages so I don't have to copy it everytime? 

It would make my life 1000x easier.

**Comment by phated** [comment]
Support questions should be directed to StackOverflow.
