### ISSUE TITLE
Maintain template folder structure

### ISSUE THREAD

**Issue by gonzaloruizdevilla** [phated/grunt-jade#6]
When compiling, I'm losing the jade templates folder structure and this is problematic for me, as all the html files get mixed in the same directory.

This commit from Richard Butler was very useful for me:
https://github.com/richardbutler/grunt-jade/commit/7e34aec091a0fdc7a1a17c8b6bf7e45fd2af07b4

It would be nice if you could merge it.

**Comment by phated** [comment]
Would the Grunt 0.4 pattern of '/path/to/dest': ['path/to/src/'] solve this for you? You can find the implementation at https://github.com/phated/grunt-jade/tree/grunt0.4

**Comment by juriejan** [comment]
That'll solve it for me.

I'll use richardbutler's branch till I can upgrade to Grunt 0.4.

**Comment by phated** [comment]
I will look into back-porting the changes to master branch as I move to the 0.4 release of this plugin.

**Comment by gonzaloruizdevilla** [comment]
What I need is Ruchard Butlers commit. I'll explain my use case:
I have a jade template in

```
/app/view/jade/list/detail.jade
```

and I want it to be compiled to

```
/app/view/list/detail.html
```

Right now the jade grunt plugin compiles it to 

```
/app/view/detail.html
```

so I lose the the folder structure (/list/).

With Butler's commit I use this configuration:

```
   jade: {
      html: {
        src: ['app/views/jade/**/*.jade'],
        dest: 'app/views',
        options: {
          basePath: 'app/views/jade',
          client: false
        }
      }
    },
```

This works thanks to the changes:

```
35   -      , files = grunt.file.expandFiles(this.file.src);
    35  +      , files = grunt.file.expandFiles(this.file.src)
    36  +      , basePath = options.basePath;

```

and

```
     44 +        , outputDir = basePath ? path.dirname(path.relative(basePath, filepath )) + "/" : ""
43 45            , src = grunt.file.read(filepath)
44      -        , outputFilename = path.basename(filepath, fileExtname)
     46 +        , outputFilename = outputDir + path.basename(filepath, fileExtname)
```

**Comment by phated** [comment]
With the new syntax, you could do:

```
jade: {
  html: {
    files: {
      'app/views': ['app/views/jade/*.jade'],
      'app/views/list': ['app/views/jade/list/*.jade']
    },
    options: {
      client: false
    }
  }
}
```

But I see how that might be a pain to specify multiple or multi-level structures, so I will take a look at implementing basePath.

**Comment by juriejan** [comment]
Shouldn't the following just keep the folder structure?

``` javascript
jade: {
  html: {
    files: {
      'app/views/**/*.js': 'app/views/jade/**/*.jade'
    }
  }
} 
```

**Comment by willthemoor** [comment]
Yes! Glad I found this. Would love to see it merged in.

**Comment by phated** [comment]
Added and published to NPM, thanks to everyone that participated on this issue.
