### ISSUE TITLE
FYI

### ISSUE THREAD

**Issue by tkellen** [phated/grunt-jade#7]
grunt.registerHelper will be depreciated in grunt 0.4.

To see how helpers will be handled in the future (using standard npm require), check out the following links:

https://github.com/gruntjs/grunt-contrib-uglify/blob/master/tasks/uglify.js#L15 https://github.com/gruntjs/grunt-contrib-uglify/blob/master/tasks/lib/min.js

PS: join us in #grunt on freenode if you have any questions!

**Comment by phated** [comment]
Thanks for the heads-up.  Just published https://github.com/phated/grunt-jade/tree/grunt0.4 but will need to update docs before 0.4.0 grunt release.
